version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - iface
    - importas
    - inamedparam
    - iotamixing
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nestif
    - nilnesserr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - cyclop
    - depguard
    - dupl
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - godoclint
    - godot
    - godox
    - gosec
    - gosmopolitan
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - modernize
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nlreturn    
    - noctx
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - perfsprint
    - recvcheck
    - revive
    - tagalign
    - testifylint
    - testpackage
    - varnamelen
    - wsl_v5
